platform :ios, '6.1'
#pod 'InfoStructure', :path => '~/Personal/wildthink/labs/InfoStructure/InfoStructure', :branch => 'develop'
pod 'InfoStructure', :path => '~/Sandbox/InfoStructure/InfoStructure/', :branch => 'develop'
pod 'REMenu', '~> 1.5'